import { useState } from 'react'
import { practiceQuestions } from '../data/questions'

export function PracticeView() {
  const [index, setIndex] = useState(0)
  const [selected, setSelected] = useState<string | null>(null)
  const question = practiceQuestions[index]
  const correct = selected === question.answer
  return <div className="!mx-auto !max-w-5xl !space-y-7"><header><p className="!mb-2 !font-mono !text-xs !uppercase !tracking-[0.18em] !text-emerald-700">Practice room</p><h1 className="!mb-2 !text-5xl !font-extrabold !tracking-[-0.07em] !text-slate-900">Sharpen your <span className="!font-serif !font-normal !italic !text-orange-500">grammar.</span></h1><p className="!text-sm !text-slate-500">A short adaptive quiz based on your recent mistakes.</p></header><section className="!rounded-3xl !bg-white !p-6 !shadow-sm sm:!p-9"><div className="mb-8 flex items-center justify-between"><span className="!font-mono !text-xs !text-slate-400">QUESTION {String(index + 1).padStart(2, '0')} / {practiceQuestions.length}</span><span className="!rounded-full !bg-orange-100 !px-3 !py-1 !text-xs !font-bold !text-orange-700">Grammar</span></div><div className="!mb-8 !rounded-2xl !bg-slate-50 !p-7"><p className="!mb-0 !text-center !text-2xl !font-bold !leading-relaxed !text-slate-800">{question.prompt}</p></div><div className="grid gap-3 sm:grid-cols-2">{question.options.map((option) => <button className={`!rounded-xl !border !p-4 !text-left !text-sm !font-semibold ${selected === option ? (option === question.answer ? '!border-emerald-500 !bg-emerald-50 !text-emerald-800' : '!border-rose-400 !bg-rose-50 !text-rose-700') : '!border-slate-200 !text-slate-700'}`} key={option} onClick={() => setSelected(option)}>{option}</button>)}</div>{selected && <div className={`mt-6 !rounded-xl !p-4 !text-sm ${correct ? '!bg-emerald-50 !text-emerald-800' : '!bg-amber-50 !text-amber-800'}`}><strong>{correct ? 'Nice work.' : `The answer is “${question.answer}”.`}</strong><p className="!mb-0 !mt-1">{question.note}</p></div>}<div className="mt-8 flex justify-end"><button className="!rounded-xl !bg-emerald-700 !px-5 !py-3 !text-sm !font-bold !text-white disabled:!opacity-40" disabled={!selected} onClick={() => { setIndex((current) => (current + 1) % practiceQuestions.length); setSelected(null) }}>Next question →</button></div></section></div>
}